In [1]:
# import necessary libraries
import pandas as pd

In [2]:
# load the dataset
urbannest_df=pd.read_csv('./data/UrbanNest_Retail_Dirty_Customer_Order_Dataset.csv')

In [3]:
# clean the column names
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   str
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: float64(4), int64(4), str(17)
memory usage: 976.7 KB

In [8]:
# convert the order_date column to datetime format
urbannest_df['order_date'] = pd.to_datetime(urbannest_df['order_date'], errors='coerce')

In [9]:
# order_date column to datetime format
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   datetime64[us]
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: datetime64[us](1), float64(4), int64(4), str(16)
memory usage: 976.7 KB

In [10]:
# sample of the dataset
urbannest_df.head()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,F,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,MALE,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [12]:
#change gender values to Male and Female

gender = urbannest_df["gender"].astype("string").str.strip().str.casefold()
urbannest_df["gender"] = gender.replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female",
})

In [14]:
#print the unique values in the gender column
urbannest_df["gender"]

0         <NA>
1         Male
2       Female
3       Female
4         Male
         ...
4995      <NA>
4996      Male
4997      <NA>
4998      Male
4999      <NA>
Name: gender, Length: 5000, dtype: string

In [16]:
# replace the values in the age_group column with a more general representation of the age group

age_group = urbannest_df["age_group"].astype("string").str.strip().str.casefold()
age_group = age_group.replace({"<na>": pd.NA, "nan": pd.NA})
age_group = age_group.str.replace(r"^(\d+)-(\d+)$", r"\1+", regex=True)
urbannest_df["age_group"] = age_group

In [17]:
# clean age_group column
urbannest_df["age_group"]

0        60+
1        46+
2        60+
3        46+
4        60+
        ...
4995    <NA>
4996     60+
4997     36+
4998     18+
4999     36+
Name: age_group, Length: 5000, dtype: string

In [19]:
# clean the city column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned city names to title case.

city = urbannest_df["city"].astype("string").str.strip().str.casefold()
city = city.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["city"] = city.str.title()

In [20]:
# clean city column

urbannest_df["city"]

0               Abuja
1              Kaduna
2              Kaduna
3       Port Harcourt
4       Port Harcourt
            ...
4995             Kano
4996           Kaduna
4997            Abuja
4998       Benin City
4999           Ibadan
Name: city, Length: 5000, dtype: string

In [22]:
# clean the region column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA.

region = urbannest_df["region"].astype("string").str.strip().str.casefold()
region = region.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["region"] = region

In [23]:
# clean region column

urbannest_df["region"]

0       north central
1          north west
2          north west
3         south south
4         south south
            ...
4995       north west
4996       north west
4997    north central
4998      south south
4999       south west
Name: region, Length: 5000, dtype: string

In [24]:
# clean the customer_segment column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA.

customer_segment=urbannest_df["customer_segment"].astype("string").str.strip().str.casefold()
customer_segment = customer_segment.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["customer_segment"] = customer_segment

In [25]:
# clean customer_segment column

urbannest_df["customer_segment"]

0       occasional
1             <NA>
2          regular
3          regular
4          premium
           ...
4995       premium
4996       regular
4997       premium
4998       premium
4999       regular
Name: customer_segment, Length: 5000, dtype: string

In [26]:
# clean the delivery_fee column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>", "nan", "free", "0", "0.00", "5", "5.00", "10", and "10.00" with their corresponding numeric values.

delivery_fee=urbannest_df["delivery_fee"].astype("string").str.strip().str.casefold()
urbannest_df["delivery_fee"] = delivery_fee.replace({
    "<na>": pd.NA,
    "nan": pd.NA,
    "free": 0.0,
    "0": 0.0,
    "0.00": 0.0,
    "5": 5.0,
    "5.00": 5.0,
    "10": 10.0,
    "10.00": 10.0,
})

In [27]:
# change the delivery_fee column to numeric type, coercing errors to NaN

urbannest_df["delivery_fee"] = pd.to_numeric(urbannest_df["delivery_fee"], errors="coerce")

In [28]:
#clean delivery_fee column

urbannest_df["delivery_fee"]

0       2500.0
1       1000.0
2          0.0
3       1000.0
4       2500.0
         ...
4995    2500.0
4996       0.0
4997    3500.0
4998    1000.0
4999    3500.0
Name: delivery_fee, Length: 5000, dtype: float64

In [29]:
# clean the payment_method column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned payment method names to title case.

payment_method=urbannest_df["payment_method"].astype("string").str.strip().str.casefold()
payment_method = payment_method.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["payment_method"] = payment_method.str.title()

In [30]:
#clean payment_method column

urbannest_df["payment_method"]

0          Bank Transfer
1                   Card
2                   Card
3       Cash On Delivery
4                 Wallet
              ...
4995       Bank Transfer
4996       Bank Transfer
4997                Ussd
4998    Cash On Delivery
4999       Bank Transfer
Name: payment_method, Length: 5000, dtype: string

In [31]:
# clean the sales_channel column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned sales channel names to title case.

sales_channel=urbannest_df["sales_channel"].astype("string").str.strip().str.casefold()
sales_channel = sales_channel.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["sales_channel"] = sales_channel.str.title()

In [32]:
# clean sales_channel column

urbannest_df["sales_channel"]

0        Mobile App
1         Instagram
2        Mobile App
3             Store
4             Store
           ...
4995      Instagram
4996    Marketplace
4997     Mobile App
4998        Website
4999          Store
Name: sales_channel, Length: 5000, dtype: string

In [33]:
# clean the order_status column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned order status names to title case.

order_status=urbannest_df["order_status"].astype("string").str.strip().str.casefold()
order_status = order_status.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["order_status"] = order_status.str.title()

In [34]:
# clean order_status column

urbannest_df["order_status"]

0       Cancelled
1       Completed
2            <NA>
3        Returned
4       Completed
          ...
4995    Completed
4996     Returned
4997    Completed
4998    Completed
4999    Completed
Name: order_status, Length: 5000, dtype: string

In [35]:
# clean the delivery_status column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned delivery status names to title case.

delivery_status=urbannest_df["delivery_status"].astype("string").str.strip().str.casefold()
delivery_status = delivery_status.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["delivery_status"] = delivery_status.str.title()

In [36]:
#clean delivery_status column

urbannest_df["delivery_status"]

0        Delivered
1          Delayed
2        Delivered
3          Delayed
4        Delivered
           ...
4995     Delivered
4996    In Transit
4997    In Transit
4998     Delivered
4999    In Transit
Name: delivery_status, Length: 5000, dtype: string

In [37]:
# clean the delivery_days column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, replace any range of days (e.g., "3-5") with the lower bound followed by a plus sign (e.g., "3+").

delivery_days = urbannest_df["delivery_days"].astype("string").str.strip().str.casefold()
delivery_days = delivery_days.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["delivery_days"] = delivery_days.str.replace(r"^(\d+)-(\d+)$", r"\1+", regex=True)

In [38]:
#clean delivery_days column

urbannest_df["delivery_days"]

0        2.0
1       14.0
2        1.0
3        5.0
4       10.0
        ...
4995    <NA>
4996    <NA>
4997     4.0
4998    13.0
4999    11.0
Name: delivery_days, Length: 5000, dtype: string

In [39]:
# clean the customer_rating column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, replace any range of ratings (e.g., "3-5") with the lower bound followed by a plus sign (e.g., "3+").

customer_rating = urbannest_df["customer_rating"].astype("string").str.strip().str.casefold()
customer_rating = customer_rating.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["customer_rating"] = customer_rating.str.replace(r"^(\d+)-(\d+)$", r"\1+", regex=True)

In [40]:
#clean customer_rating column

urbannest_df["customer_rating"]

0        4.0
1        5.0
2       <NA>
3        4.0
4        3.0
        ...
4995     4.0
4996     4.0
4997     4.0
4998     4.0
4999     4.0
Name: customer_rating, Length: 5000, dtype: string

In [41]:
# clean the return_flag column by removing leading and trailing spaces, converting to lowercase, and replacing "<na>" and "nan" with pd.NA. Finally, convert the cleaned return flag names to title case.

return_flag = urbannest_df["return_flag"].astype("string").str.strip().str.casefold()
return_flag = return_flag.replace({"<na>": pd.NA, "nan": pd.NA})
urbannest_df["return_flag"] = return_flag.str.title()

In [44]:
# clean return_flag column

urbannest_df["return_flag"]

0        No
1        No
2       Yes
3        No
4        No
       ...
4995     No
4996     No
4997    Yes
4998    Yes
4999     No
Name: return_flag, Length: 5000, dtype: string

In [45]:
# create a new column for order month

urbannest_df.head()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,<NA>,60+,Abuja,north central,occasional,...,0.20,40000.0,2500.0,Bank Transfer,Mobile App,Cancelled,Delivered,2.0,4.0,No
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46+,Kaduna,north west,<NA>,...,0.05,76000.0,1000.0,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,Female,60+,Kaduna,north west,regular,...,0.00,375000.0,0.0,Card,Mobile App,<NA>,Delivered,1.0,<NA>,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46+,Port Harcourt,south south,regular,...,0.00,375000.0,1000.0,Cash On Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,Male,60+,Port Harcourt,south south,premium,...,0.20,14000.0,2500.0,Wallet,Store,Completed,Delivered,10.0,3.0,No

In [46]:
# take a look at the last few rows of the DataFrame to ensure that the cleaning process has been successful

urbannest_df.tail()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
4995,CUST04996,ORD004996,PRD0008,2348082415426,Customer 4996,<NA>,<NA>,Kano,north west,premium,...,0.05,570000.0,2500.0,Bank Transfer,Instagram,Completed,Delivered,<NA>,4.0,No
4996,CUST04997,ORD004997,PRD0030,2348094150958,Customer 4997,Male,60+,Kaduna,north west,regular,...,0.05,42750.0,0.0,Bank Transfer,Marketplace,Returned,In Transit,<NA>,4.0,No
4997,CUST04998,ORD004998,PRD0002,2348052007276,Customer 4998,<NA>,36+,Abuja,north central,premium,...,0.15,17000.0,3500.0,Ussd,Mobile App,Completed,In Transit,4.0,4.0,Yes
4998,CUST04999,ORD004999,PRD0021,2348078351557,Customer 4999,Male,18+,Benin City,south south,premium,...,0.10,216000.0,1000.0,Cash On Delivery,Website,Completed,Delivered,13.0,4.0,Yes
4999,CUST05000,ORD005000,PRD0010,2348075328308,Customer 5000,<NA>,36+,Ibadan,south west,regular,...,0.05,35625.0,3500.0,Bank Transfer,Store,Completed,In Transit,11.0,4.0,No

In [47]:
# list the columns of the DataFrame to verify that all columns have been cleaned and are in the desired format

list(urbannest_df.columns)

['customer_id',
 'order_id',
 'product_id',
 'phone_number',
 'customer_name',
 'gender',
 'age_group',
 'city',
 'region',
 'customer_segment',
 'order_date',
 'product_category',
 'product_name',
 'quantity',
 'unit_price',
 'discount_rate',
 'order_revenue',
 'delivery_fee',
 'payment_method',
 'sales_channel',
 'order_status',
 'delivery_status',
 'delivery_days',
 'customer_rating',
 'return_flag']

In [48]:
# replace spaces and hyphens in column names with underscores, and convert to lowercase

urbannest_df.columns=urbannest_df.columns.str.strip().str.casefold().str.replace(" ", "_").str.replace("-", "_")

In [49]:
# clean column names

list(urbannest_df.columns)

['customer_id',
 'order_id',
 'product_id',
 'phone_number',
 'customer_name',
 'gender',
 'age_group',
 'city',
 'region',
 'customer_segment',
 'order_date',
 'product_category',
 'product_name',
 'quantity',
 'unit_price',
 'discount_rate',
 'order_revenue',
 'delivery_fee',
 'payment_method',
 'sales_channel',
 'order_status',
 'delivery_status',
 'delivery_days',
 'customer_rating',
 'return_flag']

In [50]:
# list the columns of the DataFrame to verify that all columns have been cleaned and are in the desired format

urbannest_df["order_year"] = urbannest_df["order_date"].dt.year

In [51]:
# clean order_year column

urbannest_df["order_year"]

0       2024
1       2024
2       2026
3       2025
4       2026
        ...
4995    2026
4996    2024
4997    2024
4998    2025
4999    2026
Name: order_year, Length: 5000, dtype: int32

In [52]:
#list the columns of the DataFrame to verify that all columns have been cleaned and are in the desired format

urbannest_df["order_month"] = urbannest_df["order_date"].dt.month

In [53]:
# clean order_month column

urbannest_df["order_month"]

0        1
1       10
2        6
3       12
4        6
        ..
4995     2
4996     4
4997     6
4998    12
4999     8
Name: order_month, Length: 5000, dtype: int32

In [54]:
#summarize the number of duplicated rows in the DataFrame

urbannest_df.duplicated().sum()

np.int64(0)

In [55]:
#drop duplicate rows from the DataFrame

urbannest_df.drop_duplicates()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag,order_year,order_month
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,<NA>,60+,Abuja,north central,occasional,...,2500.0,Bank Transfer,Mobile App,Cancelled,Delivered,2.0,4.0,No,2024,1
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46+,Kaduna,north west,<NA>,...,1000.0,Card,Instagram,Completed,Delayed,14.0,5.0,No,2024,10
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,Female,60+,Kaduna,north west,regular,...,0.0,Card,Mobile App,<NA>,Delivered,1.0,<NA>,Yes,2026,6
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46+,Port Harcourt,south south,regular,...,1000.0,Cash On Delivery,Store,Returned,Delayed,5.0,4.0,No,2025,12
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,Male,60+,Port Harcourt,south south,premium,...,2500.0,Wallet,Store,Completed,Delivered,10.0,3.0,No,2026,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST04996,ORD004996,PRD0008,2348082415426,Customer 4996,<NA>,<NA>,Kano,north west,premium,...,2500.0,Bank Transfer,Instagram,Completed,Delivered,<NA>,4.0,No,2026,2
4996,CUST04997,ORD004997,PRD0030,2348094150958,Customer 4997,Male,60+,Kaduna,north west,regular,...,0.0,Bank Transfer,Marketplace,Returned,In Transit,<NA>,4.0,No,2024,4
4997,CUST04998,ORD004998,PRD0002,2348052007276,Customer 4998,<NA>,36+,Abuja,north central,premium,...,3500.0,Ussd,Mobile App,Completed,In Transit,4.0,4.0,Yes,2024,6
4998,CUST04999,ORD004999,PRD0021,2348078351557,Customer 4999,Male,18+,Benin City,south south,premium,...,1000.0,Cash On Delivery,Website,Completed,Delivered,13.0,4.0,Yes,2025,12
4999,CUST05000,ORD005000,PRD0010,2348075328308,Customer 5000,<NA>,36+,Ibadan,south west,regular,...,3500.0,Bank Transfer,Store,Completed,In Transit,11.0,4.0,No,2026,8

In [ ]:
db_username='postgres'
password='1325'
host='localhost'
port='5432'
database='urbannest_db'
# Install once in the notebook environment if needed:
# !pip install sqlalchemy psycopg2-binary

# Ensure SQLAlchemy is installed in the same environment as this Jupyter kernel
try:
    import sqlalchemy
except ModuleNotFoundError:
    import sys
    !{sys.executable} -m pip install sqlalchemy psycopg2-binary
    import sqlalchemy
engine=sqlalchemy.create_engine(f'postgresql+psycopg2://{db_username}:{password}@{host}:{port}/{database}')
table_name = "urbannest_data"

# Upload the cleaned DataFrame to PostgreSQL
urbannest_df.to_sql(
    table_name,
    con=engine,
    if_exists="replace",
    index=False,
    method="multi"
)

print(f"Data loaded successfully into table '{table_name}' in database '{database}'")

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sqlalchemy
  Downloading sqlalchemy-2.1.3.tar.gz (10.5 MB)
     ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
      --------------------------------------- 0.3/10.5 MB ? eta -:--:--
     -- ------------------------------------- 0.8/10.5 MB 2.7 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/10.5 MB 2.5 MB/s eta 0:00:04
     ----- ---------------------------------- 1.6/10.5 MB 2.2 MB/s eta 0:00:04
     --------- ------------------------------ 2.6/10.5 MB 2.1 MB/s eta 0:00:04
     ----------- ---------------------------- 3.1/10.5 MB 2.1 MB/s eta 0:00:04
     ------------ --------------------------- 3.4/10.5 MB 2.0 MB/s eta 0:00:04
     -------------- ------------------------- 3.9/10.5 MB 2.0 MB/s eta 0:00:04
     ---------------- ----------------------- 4.5/10.5 MB 2.1 MB/s eta 0:00:03
     ------------------ --------------------- 5.0/10.5 MB 2.1 MB/s eta 0:00:03
     ------------------- -------------------- 5.2/10.5 MB 2.1 MB/s eta 0:00:03
     --------------------- ------------------ 5.8/10.5 MB 2.1 MB/s eta 0:00:03
     ----------------------- ---------------- 6.3/10.5 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 6.6/10.5 MB 2.1 MB/s eta 0:00:02
     -------------------------- ------------- 7.1/10.5 MB 2.1 MB/s eta 0:00:02
     ---------------------------- ----------- 7.6/10.5 MB 2.1 MB/s eta 0:00:02
     ----------------------------- ---------- 7.9/10.5 MB 2.1 MB/s eta 0:00:02
     ------------------------------- -------- 8.4/10.5 MB 2.1 MB/s eta 0:00:02
     --------------------------------- ------ 8.9/10.5 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 9.4/10.5 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 10.0/10.5 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 10.2/10.5 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------- 10.5/10.5 MB 2.0 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\urbannest\Lib\site-packages (from sqlalchemy) (4.16.0)
Using cached psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (pyproject.toml): started
  Building wheel for sqlalchemy (pyproject.toml): still running...
  Building wheel for sqlalchemy (pyproject.toml): finished with status 'done'
  Created wheel for sqlalchemy: filename=sqlalchemy-2.1.3-cp314-cp314-win_amd64.whl size=2050784 sha256=db4c6fa29069c5b5b844dea6b589c08ceec7bc72493487788863e7cf736f7de5
  Stored in directory: c:\users\silvi\appdata\local\pip\cache\wheels\97\ae\fc\0f8892967ba423fa2e34c3719aca22ab3f4ccad2efdb145382
Successfully built sqlalchemy
Installing collected packages: sqlalchemy, psycopg2-binary

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.13 sqlalchemy-2.1.3

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sqlalchemy
  Using cached sqlalchemy-2.1.3.tar.gz (10.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\urbannest\Lib\site-packages (from sqlalchemy) (4.16.0)
Using cached psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (pyproject.toml): started
  Building wheel for sqlalchemy (pyproject.toml): finished with status 'done'
  Created wheel for sqlalchemy: filename=sqlalchemy-2.1.3-cp314-cp314-win_amd64.whl size=2050784 sha256=e252754d39e4d3c81cc2ac63a8790fc82c4672422df73fe245be6b73d0cb4a14
  Stored in directory: c:\users\silvi\appdata\local\pip\cache\wheels\97\ae\fc\0f8892967ba423fa2e34c3719aca22ab3f4ccad2efdb145382
Successfully built sqlalchemy
Installing collected packages: sqlalchemy, psycopg2-binary

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.13 sqlalchemy-2.1.3

NameError: name 'table_name' is not defined